### ISSUE TITLE
Defining Circularity as input parameter causes error

### ISSUE THREAD

**Issue by CrownUpKid** [rquey/neper#56]
Hello,
I'm trying to create some 2D morphologies out of statistical Data. In the manual is a section, where the parameter "circularity" is used as 2D equivalent of sphericity. When i try to execute this command:
```
$NEPER -T -dim 2 -domain "square(5,5)" -n "from_morpho" -o "$MODELNAME.tess" -morpho "diameq:lognormal(1,0.42),circularity:lognormal(0.6977,0.0801)" -id $SEED
```

i get the following error: 
```
Error  :     > Variable `circularity' not found in `-morphooptigrid'.
generate.sh: line 15: 17248 Aborted                 (core dumped) $NEPER -T -dim 2 -domain "square(5,5)" -n "from_morpho" -o "$MODELNAME.tess" -morpho "diameq:lognormal(1,0.42),circularity:lognormal(0.6977,0.0801)" -id $SEED
```
Swaping out circularity for sphericity works perfectly fine. In addition, in the manual nowhere is specified, which definition of circularity is used. Also it would be nice, how the sphericity is calculated for 2D structures. I would need to analyse my EBSD data that way.
Thank you for you good work,
Thanks!

**Comment by rquey** [comment]
`circularity` is available only in `-stat` options, but you can use `sphericity` instead of it in all other options; in 2D, the sphericity is evaluated as the circularity... As for definitions,
- The _sphericity_ of a polyhedral cell is defined as the ratio of the surface area of the sphere of equivalent volume to the surface area of the cell.
- The _circularity_ of a polygonal cell is defined as the ratio of the perimeter of the circle of equivalent surface area to the perimeter of the cell.

I will fix the doc shortly, leaving this issue open for now.
